Add DAITA to `README.md`
mullvad/wireguard-go pull request #7
Opened 2024-06-10 09:26 UTC by MarkusPettersson98

This PR adds some information about DAITA to the project `README.md`.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/wireguard-go/7)

2024-06-10 14:20 UTC, Serock3 requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-go/7)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`README.md` line 59 at r1](https://reviewable.io/reviews/mullvad/wireguard-go/7#-O-1Vb1p5BFAR8kpXqqu:-O-1Vb1q1MJSFbThKA-9:b-meue5s) ([raw file](https://github.com/mullvad/wireguard-go/blob/fcc93949a7d664d527bdbf067faefd0cb199be83/README.md#L59)):*
> ```Markdown
> ### DAITA
> 
> [DAITA](https://mullvad.net/en/blog/introducing-defense-against-ai-guided-traffic-analysis-daita) is a Mullvad-specific addition to wireguard-go which integrates the [maybenot](https://github.com/maybenot-io/maybenot) framework for traffic analysis defenses. To build wireguard-go with DAITA you need to initialize the `maybenot` submodule.
> ```

Perhaps clarify that it is a nested submodule, or just provide the command `git submodule update --init --recursive wireguard-go-rs`


<!-- Sent from Reviewable.io -->

2024-06-10 16:00 UTC, Serock3 commented
Also, maybe we should add something to the very top of the README. Perhaps
```markdown
# Go Implementation of [WireGuard](https://www.wireguard.com/) - MullvadVPN fork

This is an implementation of WireGuard in Go. The fork adds support for [DAITA](#daita).
```

2024-06-11 07:44 UTC, MarkusPettersson98 reviewed
Fair! Adding this :blush:

> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-go/7#-:-O-5EWSM6YCXZBut5xUh:bbnfwll)* status: all files reviewed, 1 unresolved discussion (waiting on @Serock3)

___
*[`README.md` line 59 at r1](https://reviewable.io/reviews/mullvad/wireguard-go/7#-O-1Vb1p5BFAR8kpXqqu:-O-5EApYBIuQ7ytHlwEG:b2d6qh) ([raw file](https://github.com/mullvad/wireguard-go/blob/fcc93949a7d664d527bdbf067faefd0cb199be83/README.md#L59)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

Perhaps clarify that it is a nested submodule, or just provide the command `git submodule update --init --recursive wireguard-go-rs`
</blockquote></details>

The nested submodule structure does not apply to this repository, `maybenot` is the only submodule and can be initialized with the command that is provided just below the intro text :blush:

```
git submodule update --init
```


<!-- Sent from Reviewable.io -->

2024-06-12 07:52 UTC, Serock3 approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-go/7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MarkusPettersson98)

___
*[`README.md` line 59 at r1](https://reviewable.io/reviews/mullvad/wireguard-go/7#-O-1Vb1p5BFAR8kpXqqu:-O-AQOcXBulkuBjwF_H6:bp5zrfw) ([raw file](https://github.com/mullvad/wireguard-go/blob/fcc93949a7d664d527bdbf067faefd0cb199be83/README.md#L59)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

The nested submodule structure does not apply to this repository, `maybenot` is the only submodule and can be initialized with the command that is provided just below the intro text :blush:

```
git submodule update --init
```
</blockquote></details>

Yup, I forgot about that :sweat_smile: 


<!-- Sent from Reviewable.io -->

2024-06-12 08:54 UTC, dlon commented on README.md
> +# Go Implementation of [WireGuard](https://www.wireguard.com/) - MullvadVPN fork
Nit: MullvadVPN -> Mullvad VPN

2024-06-12 12:29 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-go/7)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Serock3)

___
*[`README.md` line 1 at r2](https://reviewable.io/reviews/mullvad/wireguard-go/7#gh-1636080061:-O-BQFJl3PoSlj0Bsg6G:bb6un1j) ([raw file](https://github.com/mullvad/wireguard-go/blob/a2b6057a963a3d532903a97551185a45dcf2fad1/README.md#L1)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: MullvadVPN -> Mullvad VPN
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-06-12 12:51 UTC, merged